name: Build Documentation

on:
  push:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install sphinx sphinx_rtd_theme
        
    - name: Build documentation
      working-directory: ./docs
      run: |
        make html
        
    - name: Create .nojekyll file
      run: |
        touch docs/_build/html/.nojekyll
        
    - name: Copy built docs to docs folder
      run: |
        # Create target directory if it doesn't exist
        mkdir -p docs/html
        # Copy the built documentation to the docs/html directory
        cp -R docs/_build/html/* docs/html/
        # Add .nojekyll file to prevent Jekyll processing
        touch docs/html/.nojekyll
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/html/
        git commit -m "Update documentation" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
