name: Build Documentation

on:
  push:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install sphinx sphinx_rtd_theme
        
    - name: Build documentation
      working-directory: ./docs
      run: |
        make html
        
    - name: Create .nojekyll file
      run: |
        touch docs/_build/html/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
        branch: gh-pages
        clean: true
        clean-exclude: |
          .nojekyll
