name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main, master, development ]
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install sphinx sphinx_rtd_theme
        
    - name: Build documentation
      working-directory: ./docs
      run: |
        make html
        
    - name: Archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages
        force_orphan: true